Comment out css properties
Typescript complains:

```
src/views/theme/styles.ts:23:26 - error TS2345: Argument of type '{ WebkitAppRegion: string; }' is not assignable to parameter of type 'CSSProperties'.
  Object literal may only specify known properties, and 'WebkitAppRegion' does not exist in type 'CSSProperties'.
```